# Generated by Django 3.2.18 on 2023-03-16 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230315_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username только буквы, цифры и @/./+/-/_', regex='^[a-zA-Z0-9@.+_-]*$')], verbose_name='Никнейм'),
        ),
    ]
