# Generated by Django 3.2.18 on 2023-03-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230318_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_author_title'),
        ),
    ]
