# Generated by Django 3.2.18 on 2023-03-19 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_auto_20230318_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'title')},
        ),
    ]
