# Generated by Django 3.2.18 on 2023-03-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230318_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='descriptions',
            new_name='description',
        ),
    ]
